version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: build
          command: |
            make build
      - run:
          name: test
          command: |
            yarn jest
      - run:
          name: verify-api-references
          command: |
            make verify-api-references
      - run:
          name: verify-code-examples
          command: |
            find ~/repo/build -name '*.html' | xargs yarn ts-node ./test/stylecheck.ts
      - store_artifacts:
          path: ~/repo/build
workflows:
  version: 2
  "Build":
    jobs:
      - build
